const RECEIVE_ISSUES = 'RECEIVE_ISSUES';
const GET_ARTICLES = 'GET_ARTICLES';
const GET_TAGS = 'GET_TAGS';
const GET_ARTICLE_BY_ID = 'GET_ARTICLE_BY_ID';
const DEL_ARTICLE_BY_ID = 'DEL_ARTICLE_BY_ID';

export { RECEIVE_ISSUES, GET_ARTICLES, GET_TAGS, GET_ARTICLE_BY_ID, DEL_ARTICLE_BY_ID }